frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_ui.urls')),
    path('user_authentication/', include('user_authentication.urls')),
    path('shoppingcart/', include('shoppingcart.urls')),
    path('order_and_payment/', include('order_and_payment.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_ui/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    Home,
    Categories,
    ProductListView,
    ProductListByCategoryView,
    SearchView,
    ProductDetailView,
    ProductEditView,
    ProductCreateView,
    ProductDeleteView,
    WishlistView,
    MessageFormView,
    UserMessagesView,
    ReplyCreateView,
    DeleteConversationView,
    About,
    
    
)

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', About.as_view(), name='about'),
    
    path('categories/', Categories.as_view(), name='categories'),
    
    path('products/', ProductListView.as_view(), name='products'),
    
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    
    path('products/<int:product_id>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    
    path('products/category/<int:category_id>/', ProductListByCategoryView.as_view(), name='product_list_by_category'),
    
    path('products/<int:product_id>/edit/',ProductEditView.as_view(), name='product-edit'),
    
    path('product_search/', SearchView.as_view(), name='product_search'),
    
    path('products/<int:product_id>/',ProductDetailView.as_view(), name='product_detail'),
    
    path('products/category/<int:category_id>/',ProductListByCategoryView.as_view(), name='product_list_by_category'),

    #Wishlist
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    
    #message
    path('message_form/<int:product_id>/<int:user_id>/', MessageFormView.as_view(), name='message_form'),
    
    path('user_messages/', UserMessagesView.as_view(), name='user_messages'),
    
    path('reply_create/', ReplyCreateView.as_view(), name='reply_create'),
    
    path('delete_conversation/<int:product_id>/', DeleteConversationView.as_view(), name='delete_conversation'),


]

user_authentication/urls.py
from django.urls import path
from .views import LoginView 


from .views import (
    LoginView,
    RegisterView,
    LogoutView,
    UserProfileView,
    UserProfileUpdateView,
    EditUserView,
    DeleteUserView,
    
    
    )


app_name = 'user_authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('edit_profile/', UserProfileUpdateView.as_view(), name='edit_profile'),
    path('edit_user/', EditUserView.as_view(), name='edit_user'),
    path('delete_account/', DeleteUserView.as_view(), name='delete_account'),


    

    
    ]

user_authentication/models.py
from django.db import models

# Create your models here.

user_authentication/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm, PasswordResetForm

class CustomUserCreationForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField(max_length=254)
    first_name = forms.CharField(max_length=150)
    last_name = forms.CharField(max_length=150)
    
    
    

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

user_authentication/views.py
# Import necessary modules and classes
from django import forms
from.forms import CustomUserCreationForm, LoginForm
from django.views.generic.edit import FormView
from django.shortcuts import render
from django.http import JsonResponse
import requests
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from requests_toolbelt.multipart.encoder import MultipartEncoder

# Define a view for user registration
class RegisterView(FormView):
    template_name = 'register.html'
    form_class = CustomUserCreationForm
    success_url = '/success/'
    
    # Render the registration form
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class()})

    # Handle form submission
    def form_valid(self, form):
        # Prepare data for API request
        data = {
        'username': form.cleaned_data.get('username'), 
        'password': form.cleaned_data.get('password'),
        'password_confirm': form.cleaned_data.get('password_confirm'),
        'email': form.cleaned_data.get('email'),
        'first_name': form.cleaned_data.get('first_name'),
        'last_name': form.cleaned_data.get('last_name')
    }
        # Send a POST request to the registration API
        response = requests.post("https://vintekapi.pythonanywhere.com/register/", json=data)
        # Handle API response
        if response.status_code == 201:
            token = response.json().get('token', '')
            self.request.session['token'] = token
            return redirect('/')  # redirect to the homepage
        return JsonResponse({'error': response.json().get('error', 'Failed to create user')}, status=400)

# Define a view for user login
class LoginView(FormView):
    template_name = 'login2.html'
    form_class = LoginForm  # use the custom form class
    success_url = '/success/'

    # Render the login form
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name, {'form': self.form_class()})

    # Handle form submission
    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        
        data = {'username': username, 'password': password}

        # Send a POST request to the login API
        response = requests.post("https://vintekapi.pythonanywhere.com/login/", data=data)

        # Handle API response
        if response.status_code == 200:
            token = response.json().get('token', '')
            user_id = response.json().get('user_id', '')
            username = response.json().get('username', '')
            self.request.session['token'] = token
            self.request.session['user_id'] = user_id
            self.request.session['username'] = username

            # Authenticate the user
            user = authenticate(self.request, username=username, password=password)

            # Check if the user was authenticated successfully
            if user is not None:
                # Log the user in
                login(self.request, user)

            return redirect('/')
        else:
            form.add_error(None, 'Invalid username or password')
            return self.form_invalid(form)

# Define a view for user logout
class LogoutView(View):
    def get(self, request, *args, **kwargs):
        if 'token' in request.session:
            # Send a POST request to the logout API
            response = requests.post('https://vintekapi.pythonanywhere.com/logout/', headers={'Authorization': f'Token {request.session["token"]}'})
            
            # Handle API response
            if response.status_code == 200:
                # Delete all user-related session data
                for key in ['token', 'user_id', 'username']:
                    if key in request.session:
                        del request.session[key]
                return redirect('user_authentication:login')  # Redirect to the login page
            else:
                return JsonResponse({'error': 'An error occurred while trying to log out'}, status=400)
        else:
            return JsonResponse({'error': 'No token in session'}, status=400)

# Define a view for user profile
class UserProfileView(View):
    def get(self, request, *args, **kwargs):
        user_id = request.session.get('user_id')
        if user_id:
            token = request.session.get('token')
            # Send a GET request to the user API
            response = requests.get(f'https://vintekapi.pythonanywhere.com/api/users/{user_id}/', headers={'Authorization': f'Token {token}'})
            # Handle API response
            if response.status_code == 200:
                user_data = response.json()
                return render(request, 'user_profile.html', {'user': user_data, 'profile_picture_url': user_data.get('profile_picture')})
            else:
                return JsonResponse({'error': 'An error occurred while trying to get user data'}, status=400)
        return JsonResponse({'error': 'No user ID in session'}, status=400)  # Default response

# Define a view for updating user profile
@method_decorator(csrf_exempt, name='dispatch')
class UserProfileUpdateView(View):
    def get(self, request, *args, **kwargs):
        user_id = request.session.get('user_id')
        if user_id:
            token = request.session.get('token')
            # Send a GET request to the user API
            response = requests.get(f'https://vintekapi.pythonanywhere.com/api/users/{user_id}/', headers={'Authorization': f'Token {token}'})
            # Handle API response
            if response.status_code == 200:
                return render(request, 'edit_profile.html', {'user': response.json()})
            else:
                return JsonResponse({'error': 'An error occurred while trying to get user data'}, status=400)
        return JsonResponse({'error': 'No user ID in session'}, status=400)

    # Handle form submission
    def post(self, request, *args, **kwargs):
        user_id = request.session.get('user_id')
        if user_id:
            token = request.session.get('token')
            # Prepare data for API request
            data = MultipartEncoder(
                fields={
                    'country': request.POST.get('country'),
                    'city': request.POST.get('city'),
                    'adress': request.POST.get('adress'),
                    'phone_number': request.POST.get('phone_number'),
                    'profile_picture': (request.FILES.get('profile_picture').name, request.FILES.get('profile_picture'), request.FILES.get('profile_picture').content_type) if request.FILES.get('profile_picture') else None,
                }
            )
            # Send a PUT request to the user API
            response = requests.put(f'https://vintekapi.pythonanywhere.com/api/users/{user_id}/', data=data, headers={'Authorization': f'Token {token}', 'Content-Type': data.content_type})
            # Handle API response
            if response.status_code == 200:
                return redirect('user_authentication:profile')
            else:
                return JsonResponse({'error': 'An error occurred while trying to update user profile'}, status=400)
        return JsonResponse({'error': 'No user ID in session'}, status=400)

# Define a view for editing user data
class EditUserView(View):
    def get(self, request, *args, **kwargs):
        user_id = request.session.get('user_id')
        if user_id:
            token = request.session.get('token')
            # Send a GET request to the user API
            response = requests.get(f'https://vintekapi.pythonanywhere.com/user/{user_id}/', headers={'Authorization': f'Token {token}'})
            # Handle API response
            if response.status_code == 200:
                return render(request, 'edit_user.html', {'user': response.json()})
            else:
                return JsonResponse({'error': 'An error occurred while trying to get user data'}, status=400)
        return JsonResponse({'error': 'No user ID in session'}, status=400)
    
    # Handle form submission
    def post(self, request, *args, **kwargs):
        user_id = request.session.get('user_id')
        if user_id:
            token = request.session.get('token')
            # Prepare data for API request
            data = {
                'username': request.POST.get('username'),
                'email': request.POST.get('email'),
                'first_name': request.POST.get('first_name'),
                'last_name': request.POST.get('last_name'),
                'password': request.POST.get('new_password'),
            }
            
            # Send a PUT request to the user API
            response = requests.put(f'https://vintekapi.pythonanywhere.com/user/{user_id}/', data=data, headers={'Authorization': f'Token {token}'})
            # Handle API response
            if response.status_code == 200:
                return redirect('user_authentication:profile')
            else:
                return JsonResponse({'error': 'An error occurred while trying to update user data'}, status=400)
            
            
class DeleteUserView(View):
    def get(self, request, *args, **kwargs):
        user_id = request.session.get('user_id')
        if user_id:
            token = request.session.get('token')
            response = requests.delete(f'https://vintekapi.pythonanywhere.com/user/{user_id}/', headers={'Authorization': f'Token {token}'})
            if response.status_code == 204:
                for key in ['token', 'user_id', 'username']:
                    if key in request.session:
                        del request.session[key]
                return redirect('user_authentication:login')

user_authentication/templates/edit_profile.html
{% extends "base.html" %} {% load static %} {% load bootstrap4 %}
<p></p>
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow" style="background-color: #2d8078">
        <div
          class="card-header text-center"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          <h2>Profile Details</h2>
        </div>
        <div
          class="card-body"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              <label for="country">Country</label>
              <input
                type="text"
                class="form-control"
                id="country"
                name="country"
                value="{{ user.country }}"
              />
            </div>
            <div class="form-group">
              <label for="city">City</label>
              <input
                type="text"
                class="form-control"
                id="city"
                name="city"
                value="{{ user.city }}"
              />
            </div>
            <div class="form-group">
              <label for="address">Address</label>
              <input
                type="text"
                class="form-control"
                id="adress"
                name="adress"
                value="{{ user.adress }}"
              />
            </div>
            <div class="form-group">
              <label for="phone_number">Phone Number</label>
              <input
                type="text"
                class="form-control"
                id="phone_number"
                name="phone_number"
                value="{{ user.phone_number }}"
              />
            </div>
            <div class="form-group">
              <label for="image">Profile Image</label>
              <input
                type="file"
                class="form-control-file"
                id="profile_picture"
                name="profile_picture"
              />
            </div>
            <p class="text-center">
              <button
                type="submit"
                class="btn"
                style="background-color: #cd4f41; color: #f4d9ae"
              >
                Save changes
              </button>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

user_authentication/templates/edit_user.html
{% extends "base.html" %} {% load static %} {% load bootstrap4 %}
<p></p>
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow" style="background-color: #2d8078">
        <div
          class="card-header text-center"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          <h2>Edit User Data</h2>
        </div>
        <div class="card-body" style="background-color: #2d8078; color: #f4d9ae"
        >
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
            <label for="username">Username</label>
            <input
                type="text"
                class="form-control"
                id="username"
                name="username"
                value="{{ user.username }}"
            />
            </div>
            <div class="form-group">
            <label for="email">Email</label>
            <input
                type="email"
                class="form-control"
                id="email"
                name="email"
                value="{{ user.email }}"
            />
            </div>
            <div class="form-group">
            <label for="first_name">First Name</label>
            <input
                type="text"
                class="form-control"
                id="first_name"
                name="first_name"
                value="{{ user.first_name }}"
            />
            </div>
            <div class="form-group">
            <label for="last_name">Last Name</label>
            <input
                type="text"
                class="form-control"
                id="last_name"
                name="last_name"
                value="{{ user.last_name }}"
            />
            </div>

            <div class="form-group">
            <label for="new_password">New Password</label>
            <input
                type="password"
                class="form-control"
                id="new_password"
                name="new_password"
                placeholder="Enter new password"
            />
            </div>

            <p class="text-center">
                <button type="submit" class="btn" style="background-color: #cd4f41; color: #f4d9ae"
                >
                    Save changes
                    </button>
            </p>
            
        </form>

        
        </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock %}
</div>

user_authentication/templates/login2.html
{% extends "base.html" %}{% load static %} {% load bootstrap4 %}
<p></p>
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow">
        <div
          class="card-header text-center"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          <h2>Login</h2>
        </div>
        <div
          class="card-body"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          {%if request.session.username %}
          <p>You are already logged in as {{ request.session.username }}.</p>
          <p><a href="/">Go to homepage</a></p>

          {% else %}
          <form method="post">
            {% csrf_token %} {% bootstrap_form form %}
            <p class="text-center">
              <button
                class="btn"
                type="submit"
                style="background-color: #cd4f41; color: #f4d9ae"
              >
                Login
              </button>
            </p>
          </form>
          {% if user.is_authenticated %}
          <p class="text-center">
            <a href="{% url 'user_authentication:logout' %}">Logout</a>
          </p>
          {% endif %}
          <p class="text-center" style="color: #f4d9ae">
            Don't have an account?
            <a
              href="{% url 'user_authentication:register' %}"
              style="color: #de9e46"
              >Register</a
            >
          </p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

user_authentication/templates/login_successful.html
{% extends "base.html" %}{% load static %} {% load bootstrap4 %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Login Successful</h2>
            <p class="text-center">Welcome, {{ username }}! You have successfully logged in.</p>
            <div class="text-center">
                <a class="btn btn-primary" href="{% url 'user_authentication:logout' %}">Click here to Logout</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_authentication/templates/logout_successful.html
{% extends "base.html" %}{% load static %} {% load bootstrap4 %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h2 class="text-center">Logout Successful</h2>
            <p class="text-center">You have been successfully logged out.</p>
            <div class="text-center">
                <a class="btn btn-primary" href="{% url 'user_authentication:login' %}">Click here to log in again</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

user_authentication/templates/register.html
{% extends "base.html" %}{% load static %} {% load bootstrap4 %}
<p></p>
{% block content %}
<div class="container py-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow">
        <div
          class="card-header text-center"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          <h2>Register</h2>
        </div>
        <div
          class="card-body"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          <form method="post">
            {% csrf_token %} {% bootstrap_form form %}
            <p class="text-center">
              <button
                class="btn"
                type="submit"
                style="background-color: #cd4f41; color: #f4d9ae"
              >
                Register
              </button>
            </p>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

user_authentication/templates/user_profile.html
{% extends "base.html" %} {% load static %} {% load bootstrap4 %}
<p></p>
{% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <!-- Increase column size to 8 -->
      <div class="card mb-3" style="background-color: #2d8078">
        <div class="card" style="background-color: #2d8078">
          <div class="row g-0">
            <div class="col-md-4">
              <img
                src="{{ profile_picture_url }}"
                class="img-fluid d-block"
                style="
                  color: #f4d9ae;
                  border: aliceblue;
                  border-width: 10px;
                  border-style: solid;
                  height: 200px;
                "
                alt="User Profile Picture"
              />
              <p class="text-center" style="color: #f4d9ae">
                <strong>Profile Picture</strong>
              </p>
              <!-- Add label -->
            </div>
            <div class="col-md-8">
              <div
                class="card-body"
                style="background-color: #2d8078; color: #f4d9ae"
              >
                <h5 class="card-title">{{ user.user.username }}</h5>
                <p class="card-text">
                  <strong>Email:</strong> {{ user.user.email }}
                </p>
                <p class="card-text">
                  <strong>First name:</strong> {{ user.user.first_name }}
                </p>
                <p class="card-text">
                  <strong>Last name:</strong> {{ user.user.last_name }}
                </p>
                {% if request.session.user_id %}
                <a
                  href="{% url 'user_authentication:edit_user' %}"
                  class="btn"
                  style="background-color: #cd4f41; color: #f4d9ae"
                  >Update User Data</a>
                  
                  <a
                    href="{% url 'user_authentication:delete_account' %}"
                    class="btn"
                    style="background-color: #cd4f41; color: #f4d9ae"
                    onclick="return confirm('Are you sure you want to delete your account? This action cannot be undone.');"
                  >Delete Account</a>
                
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="card">
        <div
          class="card-body"
          style="background-color: #2d8078; color: #f4d9ae"
        >
          <h5 class="card-title">Profile Details</h5>
          <p class="card-text"><strong>Country:</strong> {{ user.country }}</p>
          <p class="card-text"><strong>City:</strong> {{ user.city }}</p>
          <p class="card-text"><strong>Address:</strong> {{ user.adress }}</p>
          <p class="card-text">
            <strong>Phone Number:</strong> {{ user.phone_number }}
          </p>
          <!-- Rest of your code... -->
          {% if request.session.user_id %}
          <a
            href="{% url 'user_authentication:edit_profile' %}"
            class="btn"
            style="background-color: #cd4f41; color: #f4d9ae"
            >Update Profile Details</a
          >
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}