frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_ui.urls')),
    path('user_authentication/', include('user_authentication.urls')),
    path('shoppingcart/', include('shoppingcart.urls')),
    path('order_and_payment/', include('order_and_payment.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_ui/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    Home,
    Categories,
    ProductListView,
    ProductListByCategoryView,
    SearchView,
    ProductDetailView,
    ProductEditView,
    ProductCreateView,
    ProductDeleteView,
    WishlistView,
    MessageFormView,
    UserMessagesView,
    ReplyCreateView,
    DeleteConversationView,
    About,
    
    
)

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', About.as_view(), name='about'),
    
    path('categories/', Categories.as_view(), name='categories'),
    
    path('products/', ProductListView.as_view(), name='products'),
    
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    
    path('products/<int:product_id>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    
    path('products/category/<int:category_id>/', ProductListByCategoryView.as_view(), name='product_list_by_category'),
    
    path('products/<int:product_id>/edit/',ProductEditView.as_view(), name='product-edit'),
    
    path('product_search/', SearchView.as_view(), name='product_search'),
    
    path('products/<int:product_id>/',ProductDetailView.as_view(), name='product_detail'),
    
    path('products/category/<int:category_id>/',ProductListByCategoryView.as_view(), name='product_list_by_category'),

    #Wishlist
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    
    #message
    path('message_form/<int:product_id>/<int:user_id>/', MessageFormView.as_view(), name='message_form'),
    
    path('user_messages/', UserMessagesView.as_view(), name='user_messages'),
    
    path('reply_create/', ReplyCreateView.as_view(), name='reply_create'),
    
    path('delete_conversation/<int:product_id>/', DeleteConversationView.as_view(), name='delete_conversation'),


]

order_and_payment/urls.py
from django.urls import path
from .views import CheckoutView, PaymentView, OrderConfirmationView,MyOrdersView,DeleteOrderView

app_name = 'order_and_payment'



urlpatterns = [
    
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('order_confirmation/<int:order_id>/', OrderConfirmationView.as_view(), name='order_confirmation'),
    path('payment/<int:order_id>/', PaymentView.as_view(), name='payment_with_order'),
    path('my_orders/', MyOrdersView.as_view(), name='my_orders'),
    path('delete_order/<int:order_id>/', DeleteOrderView.as_view(), name='delete_order'),

    
    ]

order_and_payment/models.py
from django.db import models

# Create your models here.

order_and_payment/forms.py
from django import forms

class PaymentMethodForm(forms.Form):
    PAYMENT_CHOICES = (
        ('paypal', 'PayPal'),
        ('credit_card', 'Credit Card'),
        ('bank_transfer', 'Bank Transfer'),
    )

    payment_method = forms.ChoiceField(choices=PAYMENT_CHOICES)



class CreditCardPaymentForm(forms.Form):
    card_number = forms.CharField(max_length=16)
    card_holder = forms.CharField(max_length=255)
    expiry_month = forms.IntegerField(min_value=1, max_value=12)
    expiry_year = forms.IntegerField(min_value=2022)
    cvv = forms.CharField(max_length=3)

class PaypalPaymentForm(forms.Form):
    paypal_email = forms.EmailField()

class BankTransferPaymentForm(forms.Form):
    bank_name = forms.CharField(max_length=255)
    account_number = forms.CharField(max_length=255)
    sort_code = forms.CharField(max_length=255)

order_and_payment/views.py
from django.shortcuts import render, redirect
from django.views import View
import requests
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
import requests
from .forms import PaymentMethodForm, CreditCardPaymentForm, PaypalPaymentForm, BankTransferPaymentForm


class CheckoutView(View):
    def get(self, request, *args, **kwargs):
        token = request.session.get('token')
        if token is None:
            return redirect('login')

        headers = {'Authorization': f'Token {token}'}
        user_id = request.session.get('user_id')
        response = requests.get(f'https://vintekapi.pythonanywhere.com/api/users/{user_id}/', headers=headers)
        user = response.json()

        if user['adress'] is None:
            user['adress'] = 'No shipping address set.'

        return render(request, 'checkout.html', {'user': user})
    
    
    def post(self, request, *args, **kwargs):
        token = request.session.get('token')
        if token is None:
            return redirect('login')
        headers = {'Authorization': f'Token {token}'}

        # Get the user's shopping cart by making a GET request to the shopping cart API endpoint
        response = requests.get(f'https://vintekapi.pythonanywhere.com/api/shopping-cart/', headers=headers)
        cart = response.json()

        # Calculate the total price of the cart
        total_price = sum(float(item['product']['price']) * int(item['quantity']) for item in cart['items'])

        # Get the user ID from the session
        user_id = request.session.get('user_id')

        # Create a new order by making a POST request to the order creation API endpoint
        data = {
            'user': user_id,
            'total_price': str(total_price),
            'shipping_address': request.POST.get('shipping_address'),
        }

        response = requests.post('https://vintekapi.pythonanywhere.com/order/create/', headers=headers, json=data)

        # Check if the order was created successfully
        if response.status_code == 201:
            order = response.json()

            # Create an OrderProduct for each product in the cart
            for item in cart['items']:
                data = {
                    'order_id': order['id'],
                    'product_id': item['product']['id'],
                    'quantity': item['quantity'],
                    'price': item['product']['price'],
                }
                #print(f'Sending data: {data}')  # Print the data being sent
                response = requests.post('https://vintekapi.pythonanywhere.com/order/product/add/', headers=headers, json=data)
                if response.status_code != 201:
                    print(f'Failed to create OrderProduct: {response.status_code} {response.content}')
                else:
                    order_product = response.json()
                    print(f'Successfully created OrderProduct: {order_product}')
        
             # Check if we have an order_id
            if order['id'] is None:
                print("No order_id")
            else:
                print("We have an order_id:", order['id'])

            ## Clear the shopping cart by making a DELETE request to the clear_cart API endpoint
            response = requests.delete('https://vintekapi.pythonanywhere.com/api/shopping-cart/clear_cart/', headers=headers)

            # Check the response status code
            if response.status_code == 204:
                return redirect('order_and_payment:payment_with_order', order_id=order['id'])
            elif response.status_code == 404:
                return HttpResponse('Failed to clear shopping cart: Not Found', status=404)
            else:
                return HttpResponse('Failed to clear shopping cart: Unexpected status code', status=400)
        else:
            try:
                return render(request, 'checkout.html', {'error': 'There was an error processing your order.'})
            except Exception as e:
                return HttpResponse(f'An error occurred: {e}')
        

    
    
    
# Define a class OrderConfirmationView which inherits from Django's View class
class OrderConfirmationView(View):
    # Define the GET method for this view
    def get(self, request, *args, **kwargs):
        # Get the token from the session
        token = request.session.get('token')
        # Get the current user
        user = request.user

        # If the token is None, redirect to the login page
        if token is None:
            return redirect('login')

        # Define the headers for the API request
        headers = {'Authorization': f'Token {token}'}
        
        # Get the order_id from the URL parameters
        order_id = kwargs.get('order_id')

        # Send a GET request to the orders API to get the details of the order
        response = requests.get(f'https://vintekapi.pythonanywhere.com/api/orders/{order_id}/', headers=headers)
        print(f'Response status code: {response.status_code}')

        # If the response status code is 200, get the order from the response and render the order_confirmation.html template with the order
        if response.status_code == 200:
            order = response.json()
            print(f'Order: {order}')
            return render(request, 'order_confirmation.html', {'order': order})
        # If the response status code is not 200, render the order_confirmation.html template with an error message
        else:
            return render(request, 'order_confirmation.html', {'error': 'There was an error retrieving your order.'})
        
        
#---------Payment Frontend---------------------------------------------------------------------------------------------------------------------------------

# Define a class PaymentView which inherits from Django's View class
class PaymentView(View):
    # Define the GET method for this view
    def get(self, request, order_id=None, *args, **kwargs):
        # Get the token from the session
        token = request.session.get('token')
        # If the token is None, redirect to the login page
        if token is None:
            return redirect('login')
        # Define the headers for the API request
        headers = {'Authorization': f'Token {token}'}
        # Get the payment method from the session, if it doesn't exist, default to None
        payment_method = request.session.get('payment_method', None)
        # If the payment method is None, create a PaymentMethodForm
        if payment_method is None:
            form = PaymentMethodForm()
        # If the payment method is 'credit_card', create a CreditCardPaymentForm
        elif payment_method == 'credit_card':
            form = CreditCardPaymentForm()
        # If the payment method is 'paypal', create a PaypalPaymentForm
        elif payment_method == 'paypal':
            form = PaypalPaymentForm()
        # If the payment method is 'bank_transfer', create a BankTransferPaymentForm
        elif payment_method == 'bank_transfer':
            form = BankTransferPaymentForm()
        # Render the payment.html template with the form
        return render(request, 'payment.html', {'form': form})

    # Define the POST method for this view
    def post(self, request, order_id=None, *args, **kwargs):
        # Get the token from the session
        token = request.session.get('token')
        # If the token is None, redirect to the login page
        if token is None:
            return redirect('login')
        # Define the headers for the API request
        headers = {'Authorization': f'Token {token}'}
        # Get the payment method from the session, if it doesn't exist, default to None
        payment_method = request.session.get('payment_method', None)
        # If 'payment_method' is in the POST data, create a PaymentMethodForm with the POST data
        if 'payment_method' in request.POST:
            form = PaymentMethodForm(request.POST)
            # If the form is valid, store the payment method in the session and redirect to the payment_with_order page
            if form.is_valid():
                request.session['payment_method'] = form.cleaned_data['payment_method']
                request.session.save()  # Save the session data immediately
                return redirect('order_and_payment:payment_with_order', order_id=order_id)
        # If 'payment_method' is not in the POST data, create a form based on the payment method
        else:
            if payment_method == 'credit_card':
                form = CreditCardPaymentForm(request.POST)
            elif payment_method == 'paypal':
                form = PaypalPaymentForm(request.POST)
            elif payment_method == 'bank_transfer':
                form = BankTransferPaymentForm(request.POST)
            else:
                return HttpResponse('Invalid payment method', status=400)
            # If the form is valid, store the payment info and remove the payment method from the session
            if form.is_valid():
                payment_info = form.cleaned_data
                payment_info['method'] = payment_method
                del request.session['payment_method']
                request.session.save()
            # If the form is not valid, render the payment.html template with the form
            else:
                return render(request, 'payment.html', {'form': form})
            # Define the data to be sent with the API request
            data = {
                'order_id': order_id,
                'payment_info': payment_info,
            }
            # Send a POST request to the payment process API and store the response
            response = requests.post('https://vintekapi.pythonanywhere.com/payment/process/', headers=headers, json=data)
            # If the response status code is 200, redirect to the order_confirmation page

order_and_payment/templates/checkout.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    <div class="container" >
        <h1 class="text-center mt-5" style="font-family: 'Lobster', cursive; color: #2D8078;">Checkout</h1>

        {% if error %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endif %}

        <div class="row p-3 justify-content-center" >
            <div class="col-8 p-3" style="background-color: #2D8078; color: #f4d9ae;">
                <form id="checkoutForm" method="post" action="{% url 'order_and_payment:checkout' %}" class="mt-4">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="shipping_address">Shipping Address:</label>
                        {% if user.adress %}
                            <p id="existingAddress">Existing address: {{ user.adress }}</p>
                        {% endif %}
                        <input type="text" id="shipping_address" name="shipping_address" class="form-control" placeholder="Enter a new address">
                    </div>
                    <button type="submit" class="btn" style="background-color: #cd4f41 !important;
                    color: #f4d9ae;">Submit</button>
                </form>

            </div>
        </div>

        
    </div>

    <script>
        document.getElementById('checkoutForm').addEventListener('submit', function(e) {
            var shippingAddressInput = document.getElementById('shipping_address');
            if (shippingAddressInput.value === '') {
                var existingAddress = document.getElementById('existingAddress').textContent.replace('Existing address: ', '');
                shippingAddressInput.value = existingAddress;
            }
        });
    </script>
{% endblock %}

order_and_payment/templates/my_orders.html
{% extends 'base.html' %}
{% load order_date_filters %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6">
            <h3 class="text-center" style="font-family: 'Lobster', cursive; color: #2D8078;">My Orders</h3>

            {% for order in my_orders %}
                <div class="card mb-3">
                    <div class="card-header " style="background-color: #2d8078; color: #F4D9AE;">
                        Order ID: {{ order.id }} - Status: {{ order.status }}
                    </div>
                    <ul class="list-group list-group-flush">
                        {% for order_product in order.orderproduct_set %}
                            <li class="list-group-item">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div style="color: #1C404C;">
                                        <h6 class="mb-0">{{ order_product.product.name }}</h6>
                                        <small class="text-muted">Quantity: {{ order_product.quantity }}</small><br>
                                        <small class="text-muted">Brand: {{ order_product.product.brand }}</small><br>
                                        <small class="text-muted">Order Date at: {{ order.order_date|format_timestamp }}</small><br>

                                    </div>
                                    <span class="badge badge-light text-dark" style="background-color: #2d8078; color: #F4D9AE !important;">€ {{ order_product.product.price }}</span>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                    <div class="card-body" style="background-color: #2D8078;">
                        <p class="card-text" style="color: #F4D9AE;">Total Price: <strong>€ {{ order.total_price }}</strong></p>
                        <form method="POST" action="{% url 'order_and_payment:delete_order' order.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn" style="background-color: #cd4f41; color: #F4D9AE;">Delete</button>
                        </form>
                    </div>
                </div>
            {% empty %}
                <p>No orders found.</p>
            {% endfor %}
        </div>

        <div class="col-md-6">
            <h3 class="text-center" style="font-family: 'Lobster', cursive; color: #cd4f41;">Sold Orders  </h3>

            {% for order_product in sold_orders %}
                <div class="card mb-3">
                    <div class="card-header " style="background-color: #cd4f41; color: #F4D9AE;">
                        Order ID: {{ order_product.order }} - Buyer: {{ order_product.buyer_username }}
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <h6 class="mb-0">{{ order_product.product.name }}</h6>
                                    <small class="text-muted">Brand: {{ order_product.product.brand }}</small><br>
                                    <small class="text-muted">Quantity: {{ order_product.quantity }}</small><br>

                                </div>
                                <span class="badge badge-light text-dark" style="background-color: #cd4f41; color: #F4D9AE !important;">€ {{ order_product.product.price }}</span>
                            </div>
                        </li>
                    </ul>
                    <div class="card-body" style="background-color: #cd4f41; color: #F4D9AE;">
                        <p class="card-text">Total Price: <strong>€ {{ order_product.price }}</strong></p>
                        {% if order_product.order and order_product.order.id %}
                            <form method="POST" action="{% url 'order_and_payment:delete_order' order_product.order.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        {% endif %}
                    </div>
                </div>
            {% empty %}
                <p>No sold orders found.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

order_and_payment/templates/order_confirmation.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
    <div class="container mt-5">
        <div class="card">
            <div class="card-header" style="background-color: #2d8078; color: #F4D9AE;">
                <h1>Order Confirmation</h1>
            </div>
            <div class="card-body">
                <p><strong>Order ID:</strong> {{ order.id }}</p>
                <p><strong>Total Price:</strong> {{ order.total_price }}</p>
                <p><strong>Shipping Address:</strong> {{ order.shipping_address }}</p>
                <p><strong>Order Date:</strong> {{ order.order_date }}</p>
                <p><strong>Status:</strong> {{ order.status }}</p>

                <h2 class="mt-4">Products</h2>

                {% for order_product in order.orderproduct_set %}
                    <div class="card mt-3">
                        <div class="card-body">
                            <p><strong>Product ID:</strong> {{ order_product.product.id }}</p>
                            <p><strong>Product Name:</strong> {{ order_product.product.name }}</p>
                            <p><strong>Quantity:</strong> {{ order_product.quantity }}</p>
                            <p><strong>Price:</strong> {{ order_product.price }}</p>
                        </div>
                    </div>
                {% endfor %}

                {% if error %}
                    <div class="alert alert-danger mt-4" role="alert">
                        Error: {{ error }}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}

order_and_payment/templates/payment.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-lg-6" >
                <div class="form-container my-5">
                    <h1 class="text-center mt-5" style="font-family: 'Lobster', cursive; color: #2D8078;">Payment</h1>
                    <div class="p-3" style="background-color: #2D8078;">
                        <form class="align-middle" method="post" style="color: #F4D9AE;">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    {{ field.label_tag }}
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small>{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p style="color: red;">{{ error }}</p>
                                    {% endfor %}
                                </p>
                            {% endfor %}
                            <input class="btn" style="background-color: #cd4f41; color: #F4D9AE;" type="submit" value="Submit">
                        </form>

                    </div>
                    
                </div>
            </div>
        </div>
    </div>
{% endblock %}