frontend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_ui.urls')),
    path('user_authentication/', include('user_authentication.urls')),
    path('shoppingcart/', include('shoppingcart.urls')),
    path('order_and_payment/', include('order_and_payment.urls')),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_ui/urls.py
from django.contrib import admin
from django.urls import path

from .views import (
    Home,
    Categories,
    ProductListView,
    ProductListByCategoryView,
    SearchView,
    ProductDetailView,
    ProductEditView,
    ProductCreateView,
    ProductDeleteView,
    WishlistView,
    MessageFormView,
    UserMessagesView,
    ReplyCreateView,
    DeleteConversationView,
    About,
    
    
)

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', About.as_view(), name='about'),
    
    path('categories/', Categories.as_view(), name='categories'),
    
    path('products/', ProductListView.as_view(), name='products'),
    
    path('product_create/', ProductCreateView.as_view(), name='product_create'),
    
    path('products/<int:product_id>/delete/', ProductDeleteView.as_view(), name='product_delete'),
    
    path('products/category/<int:category_id>/', ProductListByCategoryView.as_view(), name='product_list_by_category'),
    
    path('products/<int:product_id>/edit/',ProductEditView.as_view(), name='product-edit'),
    
    path('product_search/', SearchView.as_view(), name='product_search'),
    
    path('products/<int:product_id>/',ProductDetailView.as_view(), name='product_detail'),
    
    path('products/category/<int:category_id>/',ProductListByCategoryView.as_view(), name='product_list_by_category'),

    #Wishlist
    path('wishlist/', WishlistView.as_view(), name='wishlist'),
    
    #message
    path('message_form/<int:product_id>/<int:user_id>/', MessageFormView.as_view(), name='message_form'),
    
    path('user_messages/', UserMessagesView.as_view(), name='user_messages'),
    
    path('reply_create/', ReplyCreateView.as_view(), name='reply_create'),
    
    path('delete_conversation/<int:product_id>/', DeleteConversationView.as_view(), name='delete_conversation'),


]

order_and_payment/urls.py
from django.urls import path
from .views import CheckoutView, PaymentView, OrderConfirmationView,MyOrdersView,DeleteOrderView

app_name = 'order_and_payment'



urlpatterns = [
    
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/', PaymentView.as_view(), name='payment'),
    path('order_confirmation/<int:order_id>/', OrderConfirmationView.as_view(), name='order_confirmation'),
    path('payment/<int:order_id>/', PaymentView.as_view(), name='payment_with_order'),
    path('my_orders/', MyOrdersView.as_view(), name='my_orders'),
    path('delete_order/<int:order_id>/', DeleteOrderView.as_view(), name='delete_order'),

    
    ]

shoppingcart/urls.py
from django.urls import path
from .views import ShoppingCartView, AddProductView, RemoveProductView, DeleteProductView, UpdateQuantityView

app_name = 'shoppingcart'


urlpatterns = [
    path('cart/', ShoppingCartView.as_view(), name='cart'),
    path('add-product/<int:product_id>/', AddProductView.as_view(), name='add_product'),
    path('remove-product/<int:cart_item_id>/', RemoveProductView.as_view(), name='remove_product'),
    path('delete-product/<int:cart_item_id>/', DeleteProductView.as_view(), name='delete_product'),
    path('update-quantity/<int:pk>/', UpdateQuantityView.as_view(), name='update_quantity'),
]

user_authentication/urls.py
from django.urls import path
from .views import LoginView 


from .views import (
    LoginView,
    RegisterView,
    LogoutView,
    UserProfileView,
    UserProfileUpdateView,
    EditUserView,
    DeleteUserView,
    
    
    )


app_name = 'user_authentication'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('edit_profile/', UserProfileUpdateView.as_view(), name='edit_profile'),
    path('edit_user/', EditUserView.as_view(), name='edit_user'),
    path('delete_account/', DeleteUserView.as_view(), name='delete_account'),


    

    
    ]

main_ui/models.py
from django.db import models


class HeroImage(models.Model):
    image = models.ImageField(upload_to='static/hero_images/')
    title = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.title

main_ui/forms.py
from django import forms
import requests
from django.core.cache import cache


class ProductForm(forms.Form):
    name = forms.CharField(max_length=50, required=True)
    brand = forms.CharField(max_length=50, required=False)
    model = forms.CharField(max_length=50, required=False)
    produced_year = forms.IntegerField(required=False)
    country_of_origin = forms.CharField(max_length=50, required=False)
    description = forms.CharField(widget=forms.Textarea, required=False)
    keywords = forms.CharField(max_length=1000, required=False)
    category = forms.ChoiceField(required=False)
    condition = forms.ChoiceField(required=True)
    price = forms.DecimalField(max_digits=10, decimal_places=2, required=False)
    quantity = forms.IntegerField(required=True)
    image = forms.ImageField(required=False)
    
    
    CONDITION_CHOICES = [
        ('Excellent', 'Excellent'),
        ('Very Good', 'Very Good'),
        ('Good', 'Good'),
        ('Acceptable', 'Acceptable'),
        ('As-Is', 'As-Is'),
    ]
    condition = forms.ChoiceField(choices=CONDITION_CHOICES, required=True)
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Fetch categories and conditions from cache or API
        categories = cache.get('categories')
        conditions = cache.get('conditions')
        if not categories:
            response = requests.get('https://vintekapi.pythonanywhere.com/api/categories/')
            if response.status_code == 200:
                categories = response.json()
                cache.set('categories', categories)
        if not conditions:
            response = requests.get('https://vintekapi.pythonanywhere.com/api/product_conditions/')
            if response.status_code == 200:
                conditions = response.json()
                cache.set('conditions', conditions)
        # Populate the category and condition choices
        if categories:
            self.fields['category'].choices = [(category['id'], category['name']) for category in categories]
        if conditions:
            self.fields['condition'].choices = [(condition['id'], condition['name']) for condition in conditions]
            
            


from django import forms

class ReplyForm(forms.Form):
    recipient = forms.IntegerField()
    product = forms.IntegerField()
    message = forms.CharField(widget=forms.Textarea)
    original_message_id = forms.IntegerField()  

main_ui/views.py
import requests
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import  HeroImage
import random
from django.views import View
from django.http import JsonResponse
from .forms import ProductForm
from requests_toolbelt.multipart.encoder import MultipartEncoder
from django.views.generic.edit import FormView
from .forms import ReplyForm
from django.contrib import messages
from dateutil.parser import parse

# Define a class Home which inherits from Django's TemplateView
class Home(TemplateView):
    # Define the template name for this view
    template_name = 'home.html'

    # Override the get_context_data method to add additional context
    def get_context_data(self, **kwargs):
        # Call the superclass's get_context_data method
        context = super().get_context_data(**kwargs)
        # Get all HeroImage objects and convert them to a list
        images = list(HeroImage.objects.all())
        # Shuffle the list of images
        random.shuffle(images)
        # Add the shuffled images to the context
        context['images'] = images

        # Get the user_id from the session
        user_id = self.request.session.get('user_id')
        # Add the user_id to the context
        context['user_id'] = user_id

        # Return the context
        return context
    
# -----------------Categories-------------------------------------------------------------------------------------------------------------------------------

# Define a class Categories which inherits from Django's TemplateView
class Categories(TemplateView):
    # Define the template name for this view
    template_name = 'categories.html'

    # Override the get_context_data method to add additional context
    def get_context_data(self, **kwargs):
        # Call the superclass's get_context_data method
        context = super().get_context_data(**kwargs)
        # Send a GET request to the categories API
        response = requests.get('https://vintekapi.pythonanywhere.com/api/categories/')

        # Try to convert the response to JSON, if it fails, set categories_data to an empty list
        try:
            categories_data = response.json()
        except ValueError:
            categories_data = []

        # Iterate over each category in categories_data
        for category in categories_data:
            # Send a GET request to the products API for this category
            response = requests.get(f'https://vintekapi.pythonanywhere.com/api/categories/{category["id"]}/products/')
            # If the response status code is 404, set the products for this category to an empty list and continue to the next category
            if response.status_code == 404:
                category['products'] = []
                continue
            # Try to convert the response to JSON and add the products to the category
            try:
                products = response.json()
                # For each product, build the absolute URL for the product detail page and add it to the product
                for product in products:
                    product['detail_url'] = self.request.build_absolute_uri(reverse('product_detail', kwargs={'product_id': product['id']}))
                # Add the products to the category
                category['products'] = products
            # If the conversion to JSON fails, set the products for this category to an empty list
            except ValueError:
                category['products'] = []

        # Add the categories to the context
        context['categories'] = categories_data
        # Return the context
        return context
    
# -----------------User Data Functions-------------------------------------------------------------------------------------------------------------------------------


# Define a function get_username which takes a user_id and a token as parameters
def get_username(user_id, token):
    # If the token exists, define the headers for the API request with the token, else define an empty dictionary
    headers = {'Authorization': f'Token {token}'} if token else {}
    # Send a GET request to the user API with the user_id and headers, and store the response
    response = requests.get(f'https://vintekapi.pythonanywhere.com/user/{user_id}/', headers=headers)
    # If the response status code is 200, convert the response to JSON, get the username from the user and return it
    if response.status_code == 200:
        user = response.json()
        return user['username']
    # If the response status code is not 200, return None
    else:
        return None


# -----------All products-----------------------------------------------------------------------------------------------------------------------

# Define a class ProductListView which inherits from Django's TemplateView
class ProductListView(TemplateView):
    # Define the template name for this view
    template_name = 'product_list.html'

    # Override the get_context_data method to add additional context
    def get_context_data(self, **kwargs):
        # Call the superclass's get_context_data method
        context = super().get_context_data(**kwargs)

        # Define the URL for the products API
        api_url = 'https://vintekapi.pythonanywhere.com/api/products'
        try:
            # Send a GET request to the products API and store the response
            response = requests.get(api_url)
            # Raise an exception if the response status code is not 200
            response.raise_for_status() 
            # Convert the response to JSON and store the products
            products = response.json()

            # Initialize an empty list for valid products
            valid_products = []
            # Iterate over each product in products
            for product in products:
                # If the product has an 'id' key, build the absolute URL for the product detail page, add it to the product, and add the product to valid_products
                if 'id' in product:
                    product['detail_url'] = reverse('product_detail', kwargs={'product_id': product['id']})
                    valid_products.append(product)

            # Add the valid products to the context
            context['products'] = valid_products

        # If a requests.RequestException is raised, print an error message and add an error message to the context
        except requests.RequestException as e:
            print(f"Error accessing API: {e}")
            context['error_message'] = "Failed to retrieve product data from the API."

        # If a KeyError is raised, print an error message and add an error message to the context
        except KeyError as e:
            # Handle missing keys in product data
            print(f"Missing key in product data: {e}")
            context['error_message'] = "Product data format is invalid."

        # Return the context
        return context


# -----------------Product Create-------------------------------------------------------------------------------------------------------------------------------

# Define a class ProductCreateView which inherits from Django's FormView
class ProductCreateView(FormView):
    # Define the template name for this view
    template_name = 'product_create.html'
    # Define the form class for this view
    form_class = ProductForm

    # Override the form_valid method to add additional validation
    def form_valid(self, form):
        # Get the user_id and token from the session
        user_id = self.request.session.get('user_id')
        token = None
        if user_id:
            token = self.request.session.get('token')

        # If the token is None, add an error to the form and return form_invalid
        if token is None:
            form.add_error(None, 'User is not logged in')
            return self.form_invalid(form)

        # Get the image file from the request files
        image_file = self.request.FILES.get('image')
        # If the image file exists, store the image data, else store None
        image_data = (image_file.name, image_file, image_file.content_type) if image_file else None

        # Define the data to be sent with the API request
        data = MultipartEncoder(
            fields={
                'name': form.cleaned_data.get('name'),
                'brand': form.cleaned_data.get('brand'),
                'model': form.cleaned_data.get('model'),
                'produced_year': str(form.cleaned_data.get('produced_year')), 
                'country_of_origin': form.cleaned_data.get('country_of_origin'),
                'description': form.cleaned_data.get('description'),
                'keywords': form.cleaned_data.get('keywords'),
                'category': str(form.cleaned_data.get('category')),  
                'condition': form.cleaned_data.get('condition'),
                'price': str(form.cleaned_data.get('price')),  
                'quantity': str(form.cleaned_data.get('quantity')),  
                'image': image_data,
                'user': str(user_id) 
            }
        )
        

        # Define the headers for the API request
        headers = {'Authorization': f'Token {token}', 'Content-Type': data.content_type}
        # Send a POST request to the product creation API and store the response
        response = requests.post('https://vintekapi.pythonanywhere.com/api/products/create/', data=data, headers=headers)

        # If the response status code is 201, redirect to the products page
        if response.status_code == 201:
            return redirect('products')
        # If the response status code is not 201, add an error to the form and return form_invalid
        else:
            form.add_error(None, 'Unable to create product')
            return self.form_invalid(form)
        

main_ui/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vintek</title>
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/x-icon" />
    {% load bootstrap4 %} {% bootstrap_css %}

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
    />

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Lobster&family=Pacifico&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Slackside+One&family=Yellowtail&display=swap"
      rel="stylesheet"
    />

    <!-- custom css -->
    <link rel="stylesheet" href="{% static 'custom.css' %}" />

    <!-- bootstrap-icons -->

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css"
      rel="stylesheet"
    />
  </head>
  <body class="" style="padding-top: 80px; background-color: #f4d9ae">
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
      integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
      crossorigin="anonymous"
    ></script>

    {% block content_search %} {% endblock content_search %} {% bootstrap_javascript %} 
    {% include "navbar.html" %} {% block cart_content %} {% endblock cart_content %} {% block content %} {% endblock content %}
    <!-- footer -->

    <div class="container text-center my-4">
      {% if request.session.user_id %}
      <p style="color: #2d8078;">You are logged in as <span class="text-center" style="font-family: 'Lobster', cursive; color: #2D8078;">{{ request.session.username|capfirst }}</span>.</p>

      {% else %}
      <p style="color: #2d8078;">Please <a href="{% url 'user_authentication:login' %}">log in</a>.</p>


      {% endif %}
    <footer class="footer">
      
      



      <div class="container p-3">
        <div class="row" style="background-color: #f4d9ae">
          <div class="col text-center">
            <p style="font-size: 14px; margin-bottom: 5px; color: #1c404c">
              © Vintek 2024 - <a class="text-dark text-decoration-none" href="{% url 'about' %}">About Us</a>
            </p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

main_ui/templates/home.html
{% extends "base.html" %} {% load static %}{% load bootstrap4 %} {% bootstrap_css %} {% block content %}
<div class="p-5 text-center rounded-3" style="background-color: #cd4f41">
  <div class="container">
    <div class="row">
      <div class="col-5">
        <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">



          <div class="carousel-inner">
            {% for image in images %}
            <div class="carousel-item{% if forloop.first %} active{% endif %}">
              <img class="d-block w-100 h-50" src="{{ image.image.url }}" alt="{{ image.description }}" />
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
      <div class="col-1"></div>
      <div class="col-6 d-flex align-items-center">
        <div class="d-flex flex-column align-items-center">
          <div class="row mb-3">
            <h2 class="display-1" style="color: #f4d9ae">We miss 'em too!</h2>
          </div>
          <div class="row mb-4">
            <h3 class="lead" style="color: #f4d9ae">
              But don't worry, someone has one of these and is waiting for you.
            </h3>
          </div>


          <div class="row">
            <a href="{% url 'user_authentication:login' %}"><button type="button" class="btn"
                style="background-color: #2d8078; color: #f4d9ae">
                Start here!
              </button>
            </a>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="container">
  <div class="row my-5">
    <div class="col text-center" style="color: #2d8078;">
      <img src="{% static 'logo_h_60.png' %}" alt="Vintek_Logo">
      <p class="my-4 px-5" style="line-height: 1.8em;"><i>At Vintek, you can buy and sell all those nostalgic
          technological treasures that have left a
          mark on your life, from Polaroid cameras to turntables, and who can forget Grandma's rotary phone? Join our
          community and connect with like-minded individuals who share our appreciation for vintage technology. Because
          at
          Vintek, we celebrate the timeless allure of vintage tech.</i></p>
    </div>

  </div>
  <div class="row">
    <div class="col text-center" style="font-family: 'Lobster', cursive; color: #cd4f41; line-height: 1.4em;">
      <h2>How it works?</h2>
    </div>
  </div>
  <div class="row my-4">
    <div class="col-4">
      <h5 class="text-center" style="color: #2d8078;">Create Your Product</h5>
      <img class="text-center" src="{% static 'step1.gif' %}" alt="">
    </div>
    <div class="col-4">
      <h5 class="text-center" style="color: #2d8078;">Contact Potential Clients</h5>
      <img class="text-center" src="{% static 'step2.gif' %}" alt="">
    </div>
    <div class="col-4">
      <h5 class="text-center" style="color: #2d8078;">Sell or Buy Products</h5>
      <img class="text-center" src="{% static 'step3.gif' %}" alt="">
    </div>
  </div>

</div>






{% bootstrap_javascript %} {% endblock content %}

main_ui/templates/product_detail.html
{% extends "base.html" %}
{% load static %}
{% load bootstrap4 %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <div class="card shadow p-3">
        <img class="card-img-top" src="{{ product.image }}" alt="{{ product.name }}" />
        <div class="card-body">
          <h6 class="card-title text-center" style="font-family:  'Slackside One', cursive; font-size: larger;"> {{ product.name }}</h6>
        </div>
      </div>
    </div>
    <div class="col" >
      <div class="container p-3" style="background-color: #1c404c; border-radius: 10px; color: #f4d9ae;">
        <h5 class="text-center" style="color: #de9e46;">{{ product.name }}</h5>
        <p><strong style="color: #de9e46;">Brand:</strong> {{ product.brand }}</p>
        <p><strong style="color: #de9e46;">Model:</strong> {{ product.model }}</p>
        <p><strong style="color: #de9e46;">Year:</strong> {{ product.produced_year }}</p>
        <p><strong style="color: #de9e46;">Condition:</strong> {{ product.condition }}</p>
        <p><strong style="color: #de9e46;">Details:</strong> {{ product.description }}</p>
        <p><strong style="color: #de9e46;">Available items:</strong> {{ product.quantity }}</p>
        <p><strong style="color: #de9e46;">Price:</strong> € {{ product.price }}</p>


      <!-- ... -->

        <p>
          <strong style="color: #de9e46;">Seller:</strong>
           {% if product.is_owner %}This product belongs to you
           {% else %}
           {{ product.username}} 

           {% endif %}</p>




          {% if product.user %}

           <!-- Message Form -->
           {% if product.is_owner %}
           <p></p>
           {% else %}
              {% if request.session.user_id %}
              <div class="container mt-5">
                <div class="row">
                    <div class="col-md-12 text-center">
                        <button id="messageButton" class="btn" style="background-color: #2d8078; color: #f4d9ae;">Contact Seller</button>

                {% else %}
                        <p>You need To register For more Info</p>
               {% endif %}

                        <form id="messageForm" method="post" action="{% url 'message_form' product.id product.user %}" class="mt-3" style="display: none;">
                            {% csrf_token %}
                            <input type="hidden" name="sender" value="{{ request.session.user_id }}">
                            <input type="hidden" name="recipient" value="{{ product.user }}">
                            <input type="hidden" name="product" value="{{ product.id }}">

              <p class="mb-2">
                  <strong>From:</strong> {{ request.session.username }}<br>
                  <strong>To:</strong> {{ product.username }}<br>
                  <strong>About:</strong> "{{ product.name }}"
              </p>

              <div class="form-group">
                  <textarea name="message" class="form-control" placeholder="Type your message here..."></textarea>
              </div>

              <button type="submit" class="btn" style="background-color: #2d8078; color: #f4d9ae;">Send</button>
          </form>
      </div>
  </div>
</div>
{% endif %}
<!-- ... -->

           
<!-- ... -->
          {% endif %}
          <script>
            document.getElementById('messageButton').addEventListener('click', function() {
              document.getElementById('messageForm').style.display = 'block';
              this.style.display = 'none';
            });
            </script>


<br>
<br>





        <div class="row d-flex justify-content-around">{% if request.session.user_id and not product.is_owner %}
          
            <form method="post" action="{% url 'wishlist' %}">
              {% csrf_token %}
              <input type="hidden" name="product_id" value="{{ product.id }}">
              <button type="submit" class="btn ml-3" style="background-color: #cd4f41; color: #f4d9ae;;">
                <i class="bi bi-star-fill"></i> Add to Wishlist
              </button>
            </form>



             <!-- ... -->
        <form method="post" action="{% url 'shoppingcart:add_product' product.id %}" style="display: flex; align-items: center; gap: 10px;">
          {% csrf_token %}
          <button type="submit" class="btn" style="background-color: #2d8078; color: #f4d9ae;" {% if product.quantity == 0 %}disabled{% endif %}>
            <i class="bi bi-cart-fill"></i> Add to Cart
          </button>
          <div style="display: flex; align-items: center; gap: 5px;">
            <span style="font-size: 14px; font-weight: bold;">Qty:</span>
            <input type="number" name="quantity" min="1" max="{{ product.quantity }}" value="1" style="width: 50px; border: 2px solid #2d8078; padding: 5px;">
          </div>
        </form>
        <!-- ... -->


          
        {% endif %}</div>
        {% if product.is_owner %}
        <p class="text-center">
          <button id="toggleFormBtn" class="btn  ml-3" style="background-color: #cd4f41; color: #f4d9ae;;">Edit Your Product</button>

        </p>
      
        
        <div id="editForm" style="display: none;">
          <form method="post" action="{% url 'product-edit' product.id %}" enctype="multipart/form-data" class="mt-4">
            {% csrf_token %}
            <div class="form-group">
              <label for="id_name">Name</label>
              <input type="text" name="name" value="{{ product.name }}" required class="form-control" id="id_name">
            </div>
            <div class="form-group">
              <label for="id_brand">Brand</label>
              <input type="text" name="brand" value="{{ product.brand }}" required class="form-control" id="id_brand">
            </div>
            <div class="form-group">
              <label for="id_model">Model</label>
              <input type="text" name="model" value="{{ product.model }}" required class="form-control" id="id_model">
            </div>
            <div class="form-group">
              <label for="id_produced_year">Year</label>
              <input type="number" name="produced_year" value="{{ product.produced_year }}" required class="form-control" id="id_produced_year">
            </div>
            <div class="form-group">
              <label for="id_country_of_origin">Country of Origin</label>
              <input type="text" name="country_of_origin" value="{{ product.country_of_origin }}" required class="form-control" id="id_country_of_origin">
            </div>
            <div class="form-group">
              <label for="id_description">Description</label>
              <textarea name="description" required class="form-control" id="id_description">{{ product.description }}</textarea>
            </div>
            <div class="form-group">
              <label for="id_price">Price</label>
              <input type="number" name="price" value="{{ product.price }}" required class="form-control" id="id_price">
            </div>
            <div class="form-group">
              <label for="id_quantity">Quantity</label>
              <input type="number" name="quantity" value="{{ product.quantity }}" required class="form-control" id="id_quantity">
            </div>
            <div class="row d-flex justify-content-around">
              <button type="submit" class="btn  ml-3" style="background-color: #2d8078; color: #f4d9ae;">Update</button>
              

            </div>
            
          </form>
          <div class="row d-flex justify-content-around p-2"><form method="post" action="{% url 'product_delete' product.id %}" style="display: inline;">
            {% csrf_token %}
            <button type="submit" class="btn  ml-3" style="background-color: #cd4f41; color: #f4d9ae;" onclick="return confirm('Are you sure you want to delete this product?');">Delete</button>
          </form></div>
          
          
            
          {% endif %}




      </div>
      
      
        </div>
      </div>
    </div>
  </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', function() {
  // Escuchar clics en el botón para mostrar/ocultar formulario
  document.getElementById('toggleFormBtn').addEventListener('click', function() {
    var form = document.getElementById('editForm');
    // Alternar la visibilidad del formulario
    if (form.style.display === 'none') {
      form.style.display = 'block';
    } else {
      form.style.display = 'none';
    }
  });
});
</script>
{% endblock %}